# SPDX-License-Identifier: MIT

[tool.pytest.ini_options]
python_files = ["testmanager.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--cov=manager --cov-report=term-missing"
